# SPDX-FileCopyrightText: 2024 Shota FUJI <pockawoooh@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Check files are correctly formatted

on:
  push:
    # Runs on every push
    branches:
      - "*"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          # This job does not need cache, because only `gofmt` will be used.
          cache: false
      - name: Check format with dprint
        uses: dprint/check@v2.2
